{{- include "bjw-s.common.loader.init" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-ipns-secret
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
data:
  ipns.key: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ipfs_ipns_key>"
