image:
  repository: skylenet/sourcify-docs
  tag: '{{ github.ref_name }}@sha256:8cb86dc74d651d6e1624e0b2b118bdd918d9d530b326779470c8c4e93a9e6f57'
  pullPolicy: IfNotPresent
controller:
  type: deployment
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        port: 80
env: {}
secrets:
  secretenv:
    enabled: false
    stringData: {}
probes:
  liveness:
    enabled: true
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  readiness:
    enabled: true
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  startup:
    enabled: true
    spec:
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 30
ingress:
  main:
    enabled: false
