ipfs-cluster:
  fullnameOverride: ipfs-main
  nameOverride: ipfs-main
  replicaCount: 1
  p2pNodePort:
    nodePort: 32200
  cluster:
    image:
      repository: ipfs/ipfs-cluster
      pullPolicy: IfNotPresent
      tag: "1.0.6"
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
    nodeSelector:
      dedicated: ipfs-main
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "ipfs-main"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - ipfs-main
    storage:
      storageClassName: "do-block-storage"
      volumeSize: "2Gi"

  ipfs:
    image:
      repository: ipfs/kubo
      pullPolicy: IfNotPresent
      tag: "v0.22.0"
    resources:
      requests:
        cpu: 6500m
        memory: 10000Mi
      limits:
        cpu: 7200m
        memory: 12500Mi
    extraArgs:
      - daemon
      - --migrate=true
      - --agent-version-suffix=docker
      - --enable-gc
    initScripts:
      001-peers.sh: |-
        #!/bin/sh
        set -xe
        ipfs config Peering.Peers "[ { \"ID\": \"QmcFf2FH3CEgTNHeMRGhN7HNHU1EXAxoEk6EFuSyXCsvRE\", \"Addrs\": [ \"/dnsaddr/node-1.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z\", \"Addrs\": [ \"/dnsaddr/node-2.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfFmzSDVbwexQ9Au2pt5YEXHK5xajwgaU6PpkbLWerMa\", \"Addrs\": [ \"/dnsaddr/node-3.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx\", \"Addrs\": [ \"/dnsaddr/node-4.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfVvzK4tMdFmpJjEKDUoqRgP4W9FnmJoziYX5GXJJ8eZ\", \"Addrs\": [ \"/dnsaddr/node-5.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G\", \"Addrs\": [ \"/dnsaddr/node-6.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfZP2LuW4jxviTeG8fi28qjnZScACb8PEgHAc17ZEri3\", \"Addrs\": [ \"/dnsaddr/node-7.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfgsJsMtx6qJb74akCw1M24X1zFwgGo11h1cuhwQjtJP\", \"Addrs\": [ \"/dnsaddr/node-8.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"Qmcfr2FC7pFzJbTSDfYaSy1J8Uuy8ccGLeLyqJCKJvTHMi\", \"Addrs\": [ \"/dnsaddr/node-9.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfR3V5YAtHBzxVACWCzXTt26SyEkxdwhGJ6875A8BuWx\", \"Addrs\": [ \"/dnsaddr/node-10.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"Qmcfuo1TM9uUiJp6dTbm915Rf1aTqm3a3dnmCdDQLHgvL5\", \"Addrs\": [ \"/dnsaddr/node-11.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfV2sg9zaq7UUHVCGuSvT2M2rnLBAPsiE79vVyK3Cuev\", \"Addrs\": [ \"/dnsaddr/node-12.ingress.cloudflare-ipfs.com\" ] } ]" --json
      002-gc.sh: |-
        #!/bin/sh
        set -xe
        ipfs config Datastore.StorageGCWatermark 90 --json
        ipfs config Datastore.StorageMax "70GB"
        ipfs config Datastore.GCPeriod "6h"
      003-other.sh: |-
        ipfs config Routing.AcceleratedDHTClient true --json
    nodeSelector:
      dedicated: ipfs-main
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "ipfs-main"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - ipfs-main
    storage:
      storageClassName: "do-block-storage-xfs"
      volumeSize: "100Gi"

  sharedSecret: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ipfs_main_shared_secret>"
