ipfs-cluster:
  fullnameOverride: ipfs-main
  nameOverride: ipfs-main
  replicaCount: 1
  cluster:
    image:
      repository: ipfs/ipfs-cluster
      pullPolicy: IfNotPresent
      tag: "1.0.6"
      resources: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
    storage:
      storageClassName: "do-block-storage"
      volumeSize: "2Gi"

  ipfs:
    image:
      repository: ipfs/kubo
      pullPolicy: IfNotPresent
      tag: "v0.21.0"
      resources: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
    storage:
      storageClassName: "do-block-storage-xfs"
      volumeSize: "100Gi"
