ipfs-cluster:
  fullnameOverride: ipfs-main
  nameOverride: ipfs-main
  replicaCount: 1
  p2pNodePort:
    nodePort: 32200
  cluster:
    image:
      repository: ipfs/ipfs-cluster
      pullPolicy: IfNotPresent
      tag: "1.0.6"
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
    nodeSelector:
      dedicated: ipfs-main
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "ipfs-main"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - ipfs-main
    storage:
      storageClassName: "do-block-storage"
      volumeSize: "2Gi"

  ipfs:
    image:
      repository: ipfs/kubo
      pullPolicy: IfNotPresent
      tag: "v0.21.0"
    resources:
      requests:
        cpu: 2000m
        memory: 4000Mi
      limits:
        cpu: 3200m
        memory: 5500Mi
    nodeSelector:
      dedicated: ipfs-main
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "ipfs-main"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - ipfs-main
    storage:
      storageClassName: "do-block-storage-xfs"
      volumeSize: "100Gi"

  sharedSecret: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ipfs_main_shared_secret>"
