ipfs-cluster:
  fullnameOverride: ipfs-gateway
  nameOverride: ipfs-gateway
  replicaCount: 1
  p2pNodePort:
    nodePort: 32100
  cluster:
    image:
      repository: ipfs/ipfs-cluster
      pullPolicy: IfNotPresent
      tag: "1.0.6"
      resources: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
    storage:
      storageClassName: "do-block-storage"
      volumeSize: "2Gi"

  ipfs:
    image:
      repository: ipfs/kubo
      pullPolicy: IfNotPresent
      tag: "v0.21.0"
      resources: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
    storage:
      storageClassName: "do-block-storage-xfs"
      volumeSize: "100Gi"

  sharedSecret: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ipfs_gateway_shared_secret>"
