image:
  repository: ethereum/source-verify
  tag: monitor-latest@sha256:a5a40ebc9131b993d92ec5b34d79b965a8a294fb6cda6f821348c9a6676094bc
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##

controller:
  type: statefulset
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: false
##
## Environment configuration
##
env:
  MONITOR_PORT: "80"
  MONITOR_FETCH_TIMEOUT: 300000
  REPOSITORY_PATH: /data/repository
  SOLC_REPO: /data/compilers/solc
  SOLJSON_REPO: /data/compilers/soljson
  IPFS_GATEWAY: http://ipfs-ipfs-gateway:8080/ipfs/
  NODE_URL_MAINNET: https://rpc.mainnet.ethpandaops.io
  NODE_URL_GOERLI: https://rpc.goerli.ethpandaops.io
  NODE_URL_SEPOLIA: https://rpc.sepolia.ethpandaops.io
##
## Secrets
##
secrets:
  secretenv:
    enabled: true
    stringData:
      CF_ACCESS_CLIENT_ID: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#CF_ACCESS_CLIENT_ID>"
      CF_ACCESS_CLIENT_SECRET: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#CF_ACCESS_CLIENT_SECRET>"
      INFURA_ID: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#INFURA_ID>"
      ALCHEMY_ID: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_ID>"
      ALCHEMY_ID_OPTIMISM: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_ID_OPTIMISM>"
      ALCHEMY_ID_ARBITRUM: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_ID_ARBITRUM>"
      FALLBACK_IPFS_GATEWAY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#INFURA_IPFS_GATEWAY>"
##
## Data persistence
##
persistence:
  data:
    enabled: true
    type: pvc
    existingClaim: sourcify-repository-xfs
    mountPath: /data/repository
  compilers:
    enabled: true
    type: pvc
    existingClaim: sourcify-compilers
    mountPath: /data/compilers
##
## Health probes
##
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
##
## Ingress
##
ingress:
  main:
    enabled: false
