image:
  repository: ghcr.io/ethereum/sourcify/monitor
  tag: staging@sha256:5542c0072d4a753ef55977f8639dc41eb7cd2f45e7c89c3a281c6dfa50a0b540
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##
controller:
  type: statefulset
  replicas: 0
  strategy: RollingUpdate
service:
  main:
    enabled: false
##
## Environment configuration
##
env: {}
##
## Config files / scripts
##
configMaps:
  conf:
    enabled: true
    data:
      config.json: |
        {
          "decentralizedStorages": {
            "ipfs": {
              "gateways": ["http://ipfs-ipfs-gateway:8080/ipfs/", "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#INFURA_IPFS_GATEWAY>"]
            }
          },
          "sourcifyServerURLs": ["http://sourcify-server/"]
        }
##
## Secrets
##
secrets:
  secretenv:
    enabled: true
    stringData:
      CF_ACCESS_CLIENT_ID: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#CF_ACCESS_CLIENT_ID>"
      CF_ACCESS_CLIENT_SECRET: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#CF_ACCESS_CLIENT_SECRET>"
      INFURA_API_KEY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#INFURA_API_KEY>"
      ALCHEMY_API_KEY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_API_KEY>"
      ALCHEMY_API_KEY_OPTIMISM: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_API_KEY_OPTIMISM>"
      ALCHEMY_API_KEY_ARBITRUM: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_API_KEY_ARBITRUM>"
##
## Health probes
##
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
##
## Ingress
##
ingress:
  main:
    enabled: false
