image:
  repository: ethereum/source-verify
  tag: monitor-latest@sha256:d2e02e6d9e63a28c99ce7e6b137e6c607579a4108118c339ca1e6cc53dd1ad2d
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##
controller:
  type: statefulset
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: false
##
## Environment configuration
##
env: {}
##
## Config files / scripts
##
configMaps:
  conf:
    enabled: true
    data:
      config.json: |
        {
          "decentralizedStorages": {
            "ipfs": {
              "gateways": ["http://ipfs-ipfs-gateway:8080/ipfs/", "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#INFURA_IPFS_GATEWAY>"]
            }
          },
          "sourcifyServerURLs": ["http://sourcify-server/"]
        }
##
## Secrets
##
secrets:
  secretenv:
    enabled: true
    stringData:
      CF_ACCESS_CLIENT_ID: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#CF_ACCESS_CLIENT_ID>"
      CF_ACCESS_CLIENT_SECRET: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#CF_ACCESS_CLIENT_SECRET>"
      INFURA_API_KEY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#INFURA_API_KEY>"
      ALCHEMY_API_KEY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_API_KEY>"
      ALCHEMY_API_KEY_OPTIMISM: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_API_KEY_OPTIMISM>"
      ALCHEMY_API_KEY_ARBITRUM: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_API_KEY_ARBITRUM>"
##
## Health probes
##
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
##
## Ingress
##
ingress:
  main:
    enabled: false
