image:
  repository: ethereum/source-verify
  tag: monitor-latest@sha256:b3905880ba71083203e5c2d9f5d0d9eb6494e4f9aca8fb414ab4ae54731f5c0e
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##

controller:
  type: statefulset
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: false
##
## Environment configuration
##
env: {}
##
## Config files / scripts
##
configMaps:
  conf:
    enabled: true
    data:
      config.json: |
        {
          "decentralizedStorages": {
            "ipfs": {
              "gateways": ["http://ipfs-ipfs-gateway:8080/ipfs/", "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#INFURA_IPFS_GATEWAY>"]
            }
          },
          "sourcifyServerUrls": ["https://staging.sourcify.dev/server/"]
        }
##
## Secrets
##
secrets:
  secretenv:
    enabled: true
    stringData:
      CF_ACCESS_CLIENT_ID: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#CF_ACCESS_CLIENT_ID>"
      CF_ACCESS_CLIENT_SECRET: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#CF_ACCESS_CLIENT_SECRET>"
      INFURA_API_KEY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#INFURA_API_KEY>"
      ALCHEMY_API_KEY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_API_KEY>"
##
## Health probes
##
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
##
## Ingress
##
ingress:
  main:
    enabled: false
