image:
  repository: ghcr.io/ethereum/sourcify/ui
  tag: staging@sha256:d482a517cdec59eb090b441ae9dd11f54000786e4b79624959686282ebf5c3c3
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##
controller:
  type: deployment
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        port: 80
command:
  - sh
  - -ac
  - >-
    find /usr/share/nginx/html/ -type f -exec sed -i 's#docs.sourcify.dev#docs.staging.sourcify.dev#g' {} \;; find /usr/share/nginx/html/ -type f -exec sed -i 's#playground.sourcify.dev#playground.staging.sourcify.dev#g' {} \;; /docker-entrypoint.sh nginx -g "daemon off;"
args: []
##
## Environment configuration
##
env:
##
## Secrets
##
secrets:
  secretenv:
    enabled: false # If enabled, a Secret will be created and imported via envFrom into the main application.
    stringData: {}
##
## Health probes
##
probes:
  liveness:
    enabled: true
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  readiness:
    enabled: true
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  startup:
    enabled: true
    spec:
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 30
##
## Ingress
##
ingress:
  main:
    enabled: false
