image:
  repository: ethereum/source-verify
  tag: ui-latest@sha256:34fcf53b0ad67107c25d0a0bf62e769dac44e8c175e139615e1cbe6e18f0d991
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##

controller:
  type: deployment
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        port: 80
command:
  - sh
  - -ac
  - >-
    find /usr/share/nginx/html/ -type f -exec sed -i 's#docs.sourcify.dev#docs.staging.sourcify.dev#g' {} \;; find /usr/share/nginx/html/ -type f -exec sed -i 's#playground.sourcify.dev#playground.staging.sourcify.dev#g' {} \;; /docker-entrypoint.sh nginx -g "daemon off;"
args: []
##
## Environment configuration
##
env:
  SERVER_URL: https://staging.sourcify.dev/server
  REPOSITORY_SERVER_URL: https://repo.staging.sourcify.dev
  IPNS: repo.staging.sourcify.dev
  TAG: latest
  AUTH0_ISSUERBASEURL: https://dev-htkreq1l71u1hn5l.us.auth0.com
  AUTH0_CLIENTID: epipuQWJL67dVggPvxNmAy40ggzNum9F
  AUTH0_AUDIENCE: https://sourcify.dev
##
## Secrets
##
secrets:
  secretenv:
    enabled: false # If enabled, a Secret will be created and imported via envFrom into the main application.
    stringData: {}
##
## Health probes
##
probes:
  liveness:
    enabled: true
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  readiness:
    enabled: true
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  startup:
    enabled: true
    spec:
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 30
##
## Ingress
##
ingress:
  main:
    enabled: false
