{{- if .Values.filesystemImport.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: db-fs-import
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/migration.configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                  - sourcify-static
      containers:
        - name: fs-import
          env:
          {{- toYaml .Values.filesystemImport.env | nindent 10 }}
          image: "{{ .Values.filesystemImport.image.registry }}/{{ .Values.filesystemImport.image.repository }}:{{ .Values.filesystemImport.image.tag }}"
          command: ["bash"]
          args:
            - /scripts/run-fs-import.sh
          imagePullPolicy: "{{ .Values.filesystemImport.image.pullPolicy }}"
          volumeMounts:
            - mountPath: /data/repository
              name: data
            - mountPath: "/scripts"
              name: scripts
      nodeSelector:
        dedicated: sourcify-static
      terminationGracePeriodSeconds: 60
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: sourcify-static
      volumes:
        - name: scripts
          configMap:
            name: db-migration
            defaultMode: 0500
        - name: data
          persistentVolumeClaim:
            claimName: sourcify-repository-default-xfs
{{- end }}
