image:
  repository: ethereum/source-verify
  tag: monitor-stable@sha256:7a6efa5e81d86285a107dcf3f6bd74569f8cf73ded27083692e086d36b08ef40
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##
resources:
  limits:
    cpu: "1"
    memory: 1500Mi
  requests:
    cpu: "0.8"
    memory: 1500Mi
controller:
  type: statefulset
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: false
##
## Environment configuration
##
env: {}
##
## Config files / scripts
##
configMaps:
  conf:
    enabled: true
    data:
      config.json: |
        {
          "decentralizedStorages": {
            "ipfs": {
              "gateways": ["http://ipfs-ipfs-gateway:8080/ipfs/", "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#INFURA_IPFS_GATEWAY>"]
            }
          },
          "sourcifyServerURLs": ["http://sourcify-server/"]
        }
##
## Secrets
##
secrets:
  secretenv:
    enabled: true
    stringData:
      CF_ACCESS_CLIENT_ID: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#CF_ACCESS_CLIENT_ID>"
      CF_ACCESS_CLIENT_SECRET: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#CF_ACCESS_CLIENT_SECRET>"
      INFURA_API_KEY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#INFURA_API_KEY>"
      ALCHEMY_API_KEY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_API_KEY>"
      ALCHEMY_API_KEY_OPTIMISM: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_API_KEY_OPTIMISM>"
      ALCHEMY_API_KEY_ARBITRUM: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ALCHEMY_API_KEY_ARBITRUM>"
##
## Health probes
##
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
##
## Ingress
##
ingress:
  main:
    enabled: false
