image:
  repository: ghcr.io/ethereum/sourcify/repository
  tag: master@sha256:6b431c54a375094042e14c31e66e115443991aec28c50ccd244bdbfe6ed7d961
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##
resources:
  limits:
    cpu: "0.3"
    memory: 450Mi
  requests:
    cpu: "0.1"
    memory: 350Mi
controller:
  type: deployment
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        port: 80
##
## Run pod on a specific node
##
nodeSelector:
  dedicated: sourcify-static
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "sourcify-static"
    effect: "NoSchedule"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: dedicated
              operator: In
              values:
                - sourcify-static
##
## Environment configuration
##
env: {}
##
## Secrets
##
secrets:
  secretenv:
    enabled: false # If enabled, a Secret will be created and imported via envFrom into the main application.
    stringData: {}
##
## Data persistence
##
persistence:
  data:
    enabled: true
    type: pvc
    existingClaim: sourcify-repository-default-xfs
    mountPath: /data
##
## Health probes
##
probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - -c
          - ls /data/
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  readiness:
    enabled: true
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  startup:
    enabled: true
    spec:
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 30
##
## Ingress
##
ingress:
  main:
    enabled: false
