---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sourcify-www
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 $scheme://{{ .Values.domain }}$request_uri;
spec:
  ingressClassName: ingress-nginx-public
  tls:
    - hosts:
        - "www.{{ .Values.domain }}"
      secretName: ingress-sourcify-og-www
  rules:
    - host: "www.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sourcify-ui
                port:
                  number: 80
