image:
  repository: ghcr.io/ethereum/sourcify/repository
  tag: staging@sha256:a2c1e4024da19ef5a3f3f6ce7c0d3583ebe5ae9295bd6baa457e29a0482a95a5
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##

controller:
  type: deployment
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        port: 80
##
## Environment configuration
##
env: {}
##
## Secrets
##
secrets:
  secretenv:
    enabled: false # If enabled, a Secret will be created and imported via envFrom into the main application.
    stringData: {}
##
## Data persistence
##
persistence:
  data:
    enabled: true
    type: pvc
    existingClaim: sourcify-repository-xfs
    mountPath: /data
##
## Health probes
##
probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - -c
          - ls /data/
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  readiness:
    enabled: true
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  startup:
    enabled: true
    spec:
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 30
##
## Ingress
##
ingress:
  main:
    enabled: false
