image:
  repository: amazon/aws-cli
  tag: "2.13.16@sha256:f866c465ab43bea61009ef3782e033e15e39a4acdf7aa6c38f26b43e59bd15ab"
  pullPolicy: IfNotPresent

##
## Application
##

resources:
  limits:
    cpu: 1000m
    memory: 2500Mi
  requests:
    cpu: 500m
    memory: 2000Mi

command:
  - /usr/local/bin/aws
  - s3
  - sync
  - /data/contracts
  - s3://sourcify-backup-s3/latest/repository/contracts/

controller:
  type: cronjob
  restartPolicy: Never
  cronjob:
    concurrencyPolicy: Forbid
    schedule: "* * * * *"
    startingDeadlineSeconds: 30
    successfulJobsHistory: 1
    failedJobsHistory: 1
    backoffLimit: 6

##
## Data source
##

persistence:
  data:
    enabled: true
    type: pvc
    existingClaim: sourcify-repository-xfs
    mountPath: /data

##
## Environment configuration
##

env: {}

##
## Secrets
##

secrets:
  secretenv:
    enabled: true
    stringData:
      AWS_ACCESS_KEY_ID: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#S3_SYNC_AWS_ACCESS_KEY_ID>"
      AWS_SECRET_ACCESS_KEY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#S3_SYNC_AWS_SECRET_ACCESS_KEY>"
