image:
  repository: ghcr.io/ethereum/sourcify/ui
  tag: master@sha256:314fa2236d3187f84c66a23aad6bbd6ce05d98bd79d40a439415c6748c14646a
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##
resources:
  limits:
    cpu: "0.01"
    memory: "30Mi"
  requests:
    cpu: "0.01"
    memory: "20Mi"
controller:
  type: deployment
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        port: 80
command:
  - sh
  - -ac
  - >-
    /docker-entrypoint.sh nginx -g "daemon off;"
args: []
##
## Environment configuration
##
env:
##
## Secrets
##
secrets:
  secretenv:
    enabled: false # If enabled, a Secret will be created and imported via envFrom into the main application.
    stringData: {}
    # INFURA_ID: ""
    # ALCHEMY_ID: ""
    # ALCHEMY_ID_OPTIMISM: ""
    # ALCHEMY_ID_ARBITRUM: ""
##
## Health probes
##
probes:
  liveness:
    enabled: true
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  readiness:
    enabled: true
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  startup:
    enabled: true
    spec:
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 30
##
## Ingress
##
ingress:
  main:
    enabled: false
