apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "raw-configmap.fullname" . }}
  labels:
    {{- include "raw-configmap.labels" . | nindent 4 }}
data:
  {{ .Values.key }}: |
  {{- if .Values.yaml }}
    {{- .Values.yaml | b64dec | nindent 4 }}
  {{- end }}
