image:
  repository: ghcr.io/sourcifyeth/verifier-alliance
  tag: master@sha256:0f08ae6625e4b69cf4c2f34231964248e14e3c570504c5f70f5e1822458945cc
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: image-pull-secret
##
## Application
##
controller:
  type: deployment
  replicas: 1
  strategy: RollingUpdate
service:
  main:
    enabled: false
##
## Run pod on a specific node
##
nodeSelector:
  dedicated: sourcify-static
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "sourcify-static"
    effect: "NoSchedule"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: dedicated
              operator: In
              values:
                - sourcify-static
##
## Environment configuration
##
env:
  SOURCIFY_SERVER_HOST: http://sourcify-server
  VERA_HOST: 34.159.5.50
  VERA_DB: verifier-alliance
  VERA_USER: sourcify
  VERA_PORT: 5432
##
## Secrets
##
secrets:
  secretenv:
    enabled: true
    stringData:
      VERA_PASSWORD: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#db_alliance_sourcify_password>"
##
## Health probes
##
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
