ipfs-cluster:
  fullnameOverride: ipfs-gateway
  nameOverride: ipfs-gateway
  replicaCount: 1
  p2pNodePort:
    nodePort: 32100
    initContainer:
      image:
      repository: bitnami/kubectl
      tag: v1.27.14
  cluster:
    image:
      repository: ipfs/ipfs-cluster
      pullPolicy: IfNotPresent
      tag: "1.0.6"
    resources:
      requests:
        cpu: "0.05"
        memory: 256Mi
      limits:
        cpu: "0.1"
        memory: 256Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    storage:
      storageClassName: "do-block-storage"
      volumeSize: "2Gi"

  ipfs:
    image:
      repository: ipfs/kubo
      pullPolicy: IfNotPresent
      tag: "v0.23.0"
    resources:
      requests:
        cpu: "1.5"
        memory: 2500Mi
      limits:
        cpu: "2"
        memory: 2800Mi
    extraArgs:
      - daemon
      - --migrate=true
      - --agent-version-suffix=docker
      - --enable-gc
    initScripts:
      000-migration.sh: |-
        #!/bin/sh
        set -xe
        cd /tmp
        wget https://dist.ipfs.tech/fs-repo-migrations/v2.0.2/fs-repo-migrations_v2.0.2_linux-amd64.tar.gz  -O migrations.tar.gz
        tar -xzvf migrations.tar.gz
        ./fs-repo-migrations/fs-repo-migrations -y
      001-peers.sh: |-
        #!/bin/sh
        set -xe
        ipfs config Peering.Peers "[ { \"ID\": \"QmcFf2FH3CEgTNHeMRGhN7HNHU1EXAxoEk6EFuSyXCsvRE\", \"Addrs\": [ \"/dnsaddr/node-1.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z\", \"Addrs\": [ \"/dnsaddr/node-2.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfFmzSDVbwexQ9Au2pt5YEXHK5xajwgaU6PpkbLWerMa\", \"Addrs\": [ \"/dnsaddr/node-3.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx\", \"Addrs\": [ \"/dnsaddr/node-4.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfVvzK4tMdFmpJjEKDUoqRgP4W9FnmJoziYX5GXJJ8eZ\", \"Addrs\": [ \"/dnsaddr/node-5.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G\", \"Addrs\": [ \"/dnsaddr/node-6.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfZP2LuW4jxviTeG8fi28qjnZScACb8PEgHAc17ZEri3\", \"Addrs\": [ \"/dnsaddr/node-7.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfgsJsMtx6qJb74akCw1M24X1zFwgGo11h1cuhwQjtJP\", \"Addrs\": [ \"/dnsaddr/node-8.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"Qmcfr2FC7pFzJbTSDfYaSy1J8Uuy8ccGLeLyqJCKJvTHMi\", \"Addrs\": [ \"/dnsaddr/node-9.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfR3V5YAtHBzxVACWCzXTt26SyEkxdwhGJ6875A8BuWx\", \"Addrs\": [ \"/dnsaddr/node-10.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"Qmcfuo1TM9uUiJp6dTbm915Rf1aTqm3a3dnmCdDQLHgvL5\", \"Addrs\": [ \"/dnsaddr/node-11.ingress.cloudflare-ipfs.com\" ] }, { \"ID\": \"QmcfV2sg9zaq7UUHVCGuSvT2M2rnLBAPsiE79vVyK3Cuev\", \"Addrs\": [ \"/dnsaddr/node-12.ingress.cloudflare-ipfs.com\" ] } ]" --json
      002-gc.sh: |-
        #!/bin/sh
        set -xe
        ipfs config Datastore.StorageGCWatermark 90 --json
        ipfs config Datastore.StorageMax "10GB"
        ipfs config Datastore.GCPeriod "6h"
      003-other.sh: |-
        ipfs config Routing.AcceleratedDHTClient true --json
    nodeSelector: {}
    tolerations: []
    affinity: {}
    storage:
      storageClassName: "do-block-storage-xfs"
      volumeSize: "100Gi"

  sharedSecret: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#ipfs_gateway_shared_secret>"
