image:
  repository: amazon/aws-cli
  tag: "2.13.16@sha256:f866c465ab43bea61009ef3782e033e15e39a4acdf7aa6c38f26b43e59bd15ab"
  pullPolicy: IfNotPresent

##
## Application
##

command:
  - /usr/local/bin/aws
  - s3
  - sync
  - s3://sourcify-backup-s3/stable/repository/contracts/
  - /data/contracts

controller:
  type: cronjob
  restartPolicy: Never
  cronjob:
    concurrencyPolicy: Forbid
    schedule: "15 12 * * *"
    startingDeadlineSeconds: 30
    successfulJobsHistory: 1
    failedJobsHistory: 1
    backoffLimit: 6

##
## Run pod on a specific node
##
nodeSelector:
  dedicated: sourcify-static
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "sourcify-static"
    effect: "NoSchedule"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: dedicated
          operator: In
          values:
          - sourcify-static

##
## Data source
##

persistence:
  data:
    enabled: true
    type: pvc
    existingClaim: sourcify-repository-v1-xfs
    mountPath: /data

##
## Environment configuration
##

env: {}

##
## Secrets
##

secrets:
  secretenv:
    enabled: true
    stringData:
      AWS_ACCESS_KEY_ID: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#S3_SYNC_AWS_ACCESS_KEY_ID>"
      AWS_SECRET_ACCESS_KEY: "<path:/secrets/clusters/sourcify/shared/shared.enc.yaml#S3_SYNC_AWS_SECRET_ACCESS_KEY>"
