image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

secrets:
  secretenv:
    stringData:
      #SOME_SECRET: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>"
