image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

##
## Application
##

controller:
  type: deployment
  replicas: 1
  strategy: RollingUpdate

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        port: 80

secrets:
  secretenv:
    enabled: true
    stringData:
      TEST: test
      #SOME_SECRET: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>"
