name: Helm lint
on:
  pull_request:
    paths:
      - 'environments/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/lint-helm.yaml'
  push:
    branches:
      - master
    paths:
      - 'environments/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/lint-helm.yaml'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Lint
        run: >
          helm lint
          environments/*/applications/*
          environments/*/applications-disabled/*
